### ISSUE TITLE
light theme

### ISSUE THREAD

**Issue by s-fleck** [s-fleck/shed#1]
Shed needs a light css theme for people who prefer such things.

**Comment by arushnagpal** [comment]
Hi, Can I take up this task?

**Comment by s-fleck** [comment]
Sure... you just have to modify `inst/css/shed_dark.css`. I haven't documented the *opts* argument of shed yet, but you can test shed with a custom css file like this:

```
shed(
  iris,
  informat = "csv",
  outformat = "csv",
  opts = list(
    css = system.file("css", "shed_dark.css", package = "shed"),   #  <-- PATH TO CSS FILE
    font_size = getOption("shed.font_size", 14),
    write_funs = list(
      csv  = shed:::shed_write_csv,
      csv2 = shed:::shed_write_csv2,
      tsv  = shed:::shed_write_tsv
    ),
    read_funs = list(
      csv  = shed:::shed_read_csv,
      csv2 = shed:::shed_read_csv2,
      tsv  = shed:::shed_read_tsv
    ),
    read_encoding  = union(c("guess", "UTF-8"), iconvlist()),
    write_encoding = union("UTF-8", iconvlist())
  )
```

**Comment by arushnagpal** [comment]
I am getting an error while running using a custom file like you told. The error is:
```
Error in identical(length(x), 1L) : object 'shed_write_csv' not found
Calls: shed ... stopifnot -> is_scalar_integerish -> is_scalar -> identical
Execution halted
```
Please help me debug it. I have made changes to css but not able to run it.

**Comment by s-fleck** [comment]
You have to add shed::: in front of each of the functions (I fixed the code above). Alternatively, it should also work if you load the package with `devtools::load_all()`. 

Changing options will be easier in the future, but right now i had no time to work on that

**Comment by arushnagpal** [comment]
Sorry to bother again but even after providing a valid css local path, it is giving me an error which says:

```
Error: is_css_file(opts$css) is not TRUE
Execution halted
```

**Comment by s-fleck** [comment]
opts$css must be the path to your css file. it must be a character scalar (vector of length 1) that ends in ".css"

**Comment by arushnagpal** [comment]
Thanks for your help. I created a PR. Can you review it?
